"use client";

import React, { useState, useMemo } from "react";
import CustomTable, {
  AdvancedFilterValues,
  ActionOption,
} from "@/app/(dashboard)/components/CustomTable";
import { CustomModal } from "@/app/(dashboard)/components/modals/CustomModal";
import { ENUM_MODULES } from "@/lib/types/enums";
import { useRouter } from "next/navigation";
import OfflinePaymentReferenceForm from "./OfflinePaymentReferenceForm";
import {
  useGetOfflinePaymentsQuery,
  useGetSessionsQuery,
  useGetTermsQuery,
  useGetClassesQuery,
  useGetClassArmsQuery,
  useProcessOfflinePaymentMutation,
} from "@/redux/api";
import { toast } from "sonner";
import ApprovalForm from "../offline-payment/(components)/ApprovalForm";
import RejectionForm from "../offline-payment/(components)/RejectionForm";
import { formatDate } from "@/lib/dateUtils";

interface OfflinePayment {
  id: string;
  studentName: string;
  class: string;
  invoiceNumber: string;
  amount: number;
  generatedBy: string;
  createdOn: string;
  status: "approved" | "pending" | "rejected";
}

const OfflinePaymentsTab: React.FC = () => {
  const router = useRouter();
  const [currentPage, setCurrentPage] = useState(1);
  const [rowsPerPage, setRowsPerPage] = useState(10);
  const [searchTerm, setSearchTerm] = useState("");
  const [openOfflinePaymentModal, setOpenOfflinePaymentModal] = useState(false);
  const [showApproveModal, setShowApproveModal] = useState(false);
  const [showRejectModal, setShowRejectModal] = useState(false);
  const [selectedPayment, setSelectedPayment] = useState<any>(null);
  const [isProcessing, setIsProcessing] = useState(false);
  const [processOfflinePayment] = useProcessOfflinePaymentMutation();
  const [advancedFilters, setAdvancedFilters] = useState<AdvancedFilterValues>({
    sessionId: "",
    termId: "",
    classId: "",
    classArmId: "",
    status: "",
  });

  // Fetch filter data
  const { data: sessionsData } = useGetSessionsQuery({});
  const { data: termsData } = useGetTermsQuery({});
  const { data: classesData } = useGetClassesQuery({});
  const { data: classArmsData } = useGetClassArmsQuery({});

  // Fetch offline payments with filters
  const { data: offlinePaymentsData, isLoading } = useGetOfflinePaymentsQuery({
    page: currentPage,
    limit: rowsPerPage,
    q: searchTerm,
    sessionId: advancedFilters.sessionId,
    termId: advancedFilters.termId,
    classId: advancedFilters.classId,
    classArmId: advancedFilters.classArmId,
    status: advancedFilters.status,
  });

  console.log(offlinePaymentsData, "offline");

  const sessions = useMemo(
    () =>
      sessionsData?.data?.map((session: any) => ({
        id: session.id,
        name: session.name,
      })) || [],
    [sessionsData]
  );

  const terms = useMemo(
    () =>
      termsData?.data?.map((term: any) => ({ id: term.id, name: term.name })) ||
      [],
    [termsData]
  );

  const classes = useMemo(
    () =>
      classesData?.data?.map((classItem: any) => ({
        id: classItem.id,
        name: classItem.name,
      })) || [],
    [classesData]
  );

  const classArms = useMemo(
    () =>
      classArmsData?.data?.map((arm: any) => ({
        id: arm.id,
        name: arm.name,
      })) || [],
    [classArmsData]
  );

  const statusOptions = [
    { value: "approved", label: "Approved" },
    { value: "pending", label: "Pending" },
    { value: "rejected", label: "Rejected" },
  ];

  const columns = [
    {
      key: "sn",
      label: "S/N",
      // render: (row: any) => {
      //   console.log(row, "hhjjh");
      //   return row.serialNumber;
      // },
    },
    {
      key: "studentName",
      label: "Student Name",
      render: (row: any) =>
        `${row?.student?.user?.firstname} ${row?.student?.user?.lastname}`,
    },
    {
      key: "class",
      label: "Class",
      render: (row: any) =>
        `${row.student?.class?.name} ${row.student?.classArm?.name || ""}`,
    },

    {
      key: "reference",
      label: "Invoice No.",
      render: (row: any) => `${row.invoice?.reference}`,
    },
    {
      key: "amount",
      label: "Amount",
      render: (row: any) =>
        row.amount.toLocaleString("en-NG", {
          style: "currency",
          currency: "NGN",
          minimumFractionDigits: 0,
        }),
    },

    {
      key: "generatedBy",
      label: "Generated By",
      render: (row: any) =>
        `${row.createdByUser?.firstname} ${row.createdByUser?.lastname}`,
    },

    {
      key: "createdAt",
      label: "Created On",
      render: (row: any) => `${formatDate(row.createdAt)}`,
    },
    {
      key: "status",
      label: "Status",
      render: (row: any) => (
        <div className={`status-pill status-${row.status}`}>
          {row.status.charAt(0).toUpperCase() + row.status.slice(1)}
        </div>
      ),
    },
    {
      key: "actions",
      label: "Actions",
    },
  ];

  const data = useMemo(() => {
    if (!offlinePaymentsData?.data) return [];

    return offlinePaymentsData.data.map((payment: any, index: number) => ({
      ...payment,
      serialNumber: (currentPage - 1) * rowsPerPage + index + 1,
    }));
  }, [offlinePaymentsData?.data, currentPage, rowsPerPage]);

  const getActionOptions = (item: OfflinePayment): ActionOption[] => {
    const baseActions = [
      {
        label: "View Payment",
        type: "custom" as const,
        handler: () => {
          router.push(`/fees/offline-payment/${item.id}`);
        },
        key: "view",
      },
    ];

    if (item.status === "pending") {
      baseActions.push(
        {
          label: "Approve",
          type: "custom" as const,
          handler: () => {
            setSelectedPayment(item);
            setShowApproveModal(true);
          },
          key: "approve",
        },
        {
          label: "Reject",
          type: "custom" as const,
          handler: () => {
            setSelectedPayment(item);
            setShowRejectModal(true);
          },
          key: "reject",
        }
      );
    }

    if (item.status === "approved") {
      baseActions.push({
        label: "Download Receipt",
        type: "custom" as const,
        handler: () => {
          console.log("Download receipt:", item);
        },
        key: "download",
      });
    }

    return baseActions;
  };

  const handleAdvancedFilterChange = (newFilters: AdvancedFilterValues) => {
    setAdvancedFilters(newFilters);
    setCurrentPage(1); // Reset to first page when filters change
  };

  const handleApprove = async () => {
    if (!selectedPayment) return;
    setIsProcessing(true);
    try {
      await processOfflinePayment({
        id: selectedPayment.id,
        approve: true,
      }).unwrap();
      toast.success("Payment approved successfully!");
      setShowApproveModal(false);
      router.refresh();
    } catch (error: any) {
      toast.error(error?.data?.message || "Failed to approve payment.");
    } finally {
      setIsProcessing(false);
    }
  };

  const handleReject = async (reason: string) => {
    if (!selectedPayment) return;
    setIsProcessing(true);
    try {
      await processOfflinePayment({
        id: selectedPayment.id,
        approve: false,
        rejectionReason: reason,
      }).unwrap();
      toast.success("Payment rejected successfully!");
      setShowRejectModal(false);
      router.refresh();
    } catch (error: any) {
      toast.error(error?.data?.message || "Failed to reject payment.");
    } finally {
      setIsProcessing(false);
    }
  };

  return (
    <div className='space-y-4'>
      <CustomTable
        title='Offline Payments'
        columns={columns}
        data={data}
        filters={{
          showSearch: true,
          showFilter: false,
          showAdvancedFilters: true,
          showSessionFilter: true,
          showTermFilter: true,
          showClassFilter: true,
          showClassArmFilter: true,
          showStatusFilter: true,
        }}
        currentPage={currentPage}
        onPageChange={setCurrentPage}
        rowsPerPage={rowsPerPage}
        onRowsPerPageChange={setRowsPerPage}
        searchTerm={searchTerm}
        onSearchChange={setSearchTerm}
        totalItems={offlinePaymentsData?.total || 0}
        getActionOptions={getActionOptions}
        isSearching={isLoading}
        // Advanced filter props
        advancedFilterValues={advancedFilters}
        onAdvancedFilterChange={handleAdvancedFilterChange}
        sessions={sessions}
        terms={terms}
        classes={classes}
        classArms={classArms}
        statusOptions={statusOptions}
        showActionButton={true}
        actionButtonText='Add Offline Payment'
        onActionButtonClick={() => setOpenOfflinePaymentModal(true)}
      />

      <CustomModal
        open={openOfflinePaymentModal}
        onOpenChange={setOpenOfflinePaymentModal}
        type={ENUM_MODULES.OFFLINE_PAYMENT}
        status='create'
        title='Add Offline Payment'
        description='Enter the invoice reference to proceed with offline payment creation.'
      >
        <OfflinePaymentReferenceForm
          onClose={() => setOpenOfflinePaymentModal(false)}
        />
      </CustomModal>

      {/* Approval Modal */}
      <CustomModal
        open={showApproveModal}
        onOpenChange={setShowApproveModal}
        type={ENUM_MODULES.OFFLINE_PAYMENT}
        status='approve'
        title='Approve Offline Payment'
        description='Are you sure you want to approve this offline payment?'
      >
        <ApprovalForm
          paymentId={selectedPayment?.id}
          onClose={() => setShowApproveModal(false)}
          onApprove={handleApprove}
          isProcessing={isProcessing}
        />
      </CustomModal>

      {/* Rejection Modal */}
      <CustomModal
        open={showRejectModal}
        onOpenChange={setShowRejectModal}
        type={ENUM_MODULES.OFFLINE_PAYMENT}
        status='reject'
        title='Reject Offline Payment'
        description='Please provide a reason for rejecting this payment.'
      >
        <RejectionForm
          paymentId={selectedPayment?.id}
          onClose={() => setShowRejectModal(false)}
          onReject={handleReject}
          isProcessing={isProcessing}
        />
      </CustomModal>
    </div>
  );
};

export default OfflinePaymentsTab;
