import type { Metadata } from "next";
import { Inter, Lato } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/lib/ReduxProvider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: "700",
});

export const metadata: Metadata = {
  title: "X-Portal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${inter.variable} ${lato.variable} antialiased font-inter max-w-[1440px] mx-auto`}
      >
        <ReduxProvider>
          {/* <Suspense fallback={<Loader />}> */}
          {children}
          {/* </Suspense> */}
        </ReduxProvider>
      </body>
    </html>
  );
}
